name: flutter_scaffold
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  random_string: ^2.1.0
  logger: ^1.0.0 # for logging
  package_info: '^2.0.0' # for info on the app itself.

  #UI
  toggle_switch: ^0.1.9 # for toggle switch UI.
  rflutter_alert: ^2.0.2 # for customizing dialog UI.
  blobs: ^1.2.0 # for creating blobs.

  #internationalisation:
  intl: ^0.17.0 # for formatting
  country_code_picker: ^2.0.1 # for selecting countries
  flutter_localizations:
    sdk: flutter
    
  #device access plugins
  path_provider: ^2.0.1 # for access to phone storage
  path: ^1.8.0 # for access to phone storage
  device_info: '^2.0.0' # for getting device info
  device_apps: ^2.1.1 # for getting installed apps
  app_settings: ^4.1.0 # for access to phone settings
  shared_preferences: ^2.0.5 # for storing var on device
  connectivity: '^3.0.3' #for access to phone network
  wifi_info_flutter: ^2.0.0 # for getting detailed wifi info
  sms: ^0.2.4 # for access to sms
  permission_handler: ^7.1.0 # for requesting permissions and oppening app settings
  flutter_share: ^2.0.0 # for sharing file, links, ect with other apps
  # android_device_info: ^1.0.0 # for getting info about many device features
  contacts_service: ^0.6.1 # for access to contacts list

  #State management
  provider: ^5.0.0
  get_it: ^7.1.3

  #web plugin
  http: ^0.13.3 
  url_launcher: ^6.0.3 # for launching web links in browser
  cached_network_image: ^3.0.0 #for saving cached img 
  flutter_spinkit: ^5.0.0 # for loading icons

  #camera and media plugins
  file_picker: ^3.0.1 #for selecting files
  camera: ^0.8.1 # for access to cameras
  cached_video_player: ^1.0.3 # for playing & caching videos
  image_gallery_saver: ^1.6.9 # for saving media to gallery
  video_thumbnail: ^0.3.3 # for creating thumbnails from video
  photo_view: ^0.11.1 # for hangling images/photos
  exif: ^2.1.0 # for image metadata

  #location plugins
  geolocator: ^7.0.3 # for getting geolocation
  google_maps_flutter: ^2.0.3 # for adding google maps to app
  geoflutterfire: ^3.0.0-nullsafety.3 # for uploading geolocation to firebase

  #firebase plugins
  firebase_core: ^1.1.1 # the mother of firebase plugins 
  firebase_analytics: ^8.0.4 # for analytics
  firebase_auth: ^1.1.4 # for user auth
  firebase_storage: ^8.0.6 # for up/dwnloading data to firestore
  cloud_firestore: ^2.1.0 # for up/dwnloading files to db
  firebase_messaging: ^9.1.4 # for push notifications


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 # for creating launcher Icons

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/flutter_logo1.png"
  adaptive_icon_backgound: "#FFC200"
  adaptive_icon_foreground: "dev_assets/flutter_logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/default_avatar.png
   - assets/images/flutter_logo1.png
   - assets/map_styles/dark_map_style.json
   - assets/map_styles/light_map_style.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf

 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



